### ISSUE TITLE
Could not find 'VimSdk::Vim::ResourcePool

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-vsphere-cpi-release#11]
take from https://github.com/cloudfoundry/cf-mysql-release/issues/134

Could anyone help me on this please?

```
Started compiling packages
Started compiling packages > cluster-schema-verifier/a2f8659250e5b51a7f5d0b0fdff5dbdc5ee98895
Started compiling packages > cli/41edd6a70de171fcefd9328c5a616a03e9c88677
Started compiling packages > mysqlclient/ce95f8ac566f76b650992987d5282ee473356e43
Started compiling packages > ruby/a57562f234ecf56581a73f2e18715f19ea74e9f1
Failed compiling packages > mysqlclient/ce95f8ac566f76b650992987d5282ee473356e43: Unknown CPI error 'Unknown' with message 'Could not find 'VimSdk::Vim::ResourcePool': {:root=>
#<VimSdk::Vim::ResourcePool:0x005559933b4380
```

**Comment by ljfranklin** [comment]
@cpraveen412 we'll see if we can reproduce this. In the meantime, can you tell us which version of the vSphere CPI you are using? It should be listed in your BOSH Director manifest.

**Comment by ljfranklin** [comment]
@cpraveen412: We suspect that the vSphere Resource Pool `CF-Datastore2` is not accessible from within the vSphere Cluster `CF-Cluster` or does not exist — perhaps `CF-Datastore2` refers to a datastore and not a Resource Pool?

We opened a bug to make the error message more readable, e.g. "Resource Pool XXXXX is not accessible from Cluster YYYYY or does not exist." https://www.pivotaltracker.com/story/show/132845249

**Comment by cpraveen412** [comment]
hi @ljfranklin 
I'm using Version 29

**Comment by cpraveen412** [comment]
Hi @ljfranklin 
Thank you for mentioning "Resource Pool". I went back to my environment and created a resource pool. Now it started deploying.

**Comment by crdant** [comment]
I came across this when seeing the same error deploying a director. It's not the same case, but I do know that my resource pool exists and the user I'm deploying as can access it and create machines in it. I'm trying to figure out if this is issue is still open or not since it was tagged "open-for-contibution" and "planned-enhancement" after @cpraveen412 suggested it was resolved.

Is there still an open issue around this error?

**Comment by cdutra** [comment]
Hi @crdant, what version of the vSphere CPI are you using? Could you paste a snippet of you manifest where specifies the `resource_pool` property? Thanks

**Comment by crdant** [comment]
In my case I'm using the [Kubo deployment scripts](https://github.com/cloudfoundry-incubator/kubo-deployment) to deploy a new director. It generates a manifest through a few steps of interpolation. The failure is when creating the stemcell. I can create a VM in the same resource pool as the same user with the `govc` cli.

The relevant snippet (which appears twice):

```
    vcenter:
      address: garundasana.crdant.net
      datacenters:
      - clusters:
        - primary-cluster:
            resource_pool: /home-lab/host/primary-cluster/Resources/zone-1
        datastore_pattern: ssd
        disk_path: kubo-disks
        name: home-lab
        persistent_datastore_pattern: ssd
        template_folder: kubo-templates
        vm_folder: kubo-vms
```

The CPI is version 44.
