### ISSUE TITLE
Datastore usage appears unbalanced after recent upgrades

### ISSUE THREAD

**Issue by thelangley** [cloudfoundry/bosh-vsphere-cpi-release#174]
**The (potential) Bug**
We've recently moved to vsphere-cpi v51.0.2 from v50 and upgraded our vCenters to 6.5 u2c

We're finding that when a new stemcell is being deployed, it has a tendency to have a "favourite" Datastore so much so that it tries to almost fill it to 100%, even if loads of the others have a fair amount free.

```
- type: replace
  path: /instance_groups/name=bosh/properties/vcenter?
  value: &vcenter
    address: ((fqdn))
    user: ((user))
    password: ((theword))
    datacenters:
    - name: ((my_dc_name))
      vm_folder: ((my_folder))
      template_folder: ((my_template_folder))
      datastore_pattern: ((my_datastore_pattern))
      persistent_datastore_pattern: ((my_persistent_disk_datastore_pattern))
      disk_path: ((my_amazing_path))
      clusters:
      - ((vsphere_cluster)): { ((poolies_info)) }
```

**To Reproduce**
1. Ensure you have many datastores in vCenter available for action
2. Define them as a regex and use the pattern in your ops file
3. Deploy
4. Recreate the things
5. Recreate the things

Over time you will see one datastore gets more and more full

**CPI Error Log**
This is no error in the logs but I can see the decisions being made.

It's using the regex nicely to find all the Datastores which match but then the roll of the dice usually selects a particular one.

```
D, [2018-11-23T12:29:16.747104 #31769] DEBUG -- [req_id cpi-212057]: All clusters provided: {"my_amazing_cluster"=>#<VSphereCloud::ClusterConfig:xxxxxx @name="my_amazing_cluster", @config={"resource_pool"=>"my_amazing_resource_pool"}>}
D, [2018-11-23T12:29:16.747207 #31769] DEBUG -- [req_id cpi-212057]: Running method 'FindByInventoryPath'...
I, [2018-11-23T12:29:16.783249 #31769]  INFO -- [req_id cpi-212057]: Using global ephemeral disk datastore pattern: my_amazing_datastore_[0-9]{2}
I, [2018-11-23T12:29:16.790485 #31769]  INFO -- [req_id cpi-212057]: Initiating VM Allocator with VM Placement Criteria: Disk Config: [Disk ==> Disk CID: Size:10240 Ephemeral:true Target-DS:my_amazing_datastore_[0-9]{2} Existing-DS:]  Req Memory: 4096  Mem Headroom: 128
I, [2018-11-23T12:29:16.790552 #31769]  INFO -- [req_id cpi-212057]: Gathering vm placement resources for vm placement allocator pipeline
D, [2018-11-23T12:29:16.823403 #31769] DEBUG -- [req_id cpi-212057]: Found requested resource pool: <[Vim.ResourcePool] resgroup-xxxx>
D, [2018-11-23T12:29:16.833596 #31769] DEBUG -- [req_id cpi-212057]: Filter VM Placement Cluster: my_amazing_cluster Memory: 1907108 for free memory required: 4224
D, [2018-11-23T12:29:16.833696 #31769] DEBUG -- [req_id cpi-212057]: Filter VM Placement Cluster : my_amazing_cluster hosts:  datastores: [<Datastore: / my_amazing_datastore_00 >, <Datastore: / my_amazing_datastore_01 >, <Datastore: / my_amazing_datastore_02>] for combination of DS satisfying disk configurations
D, [2018-11-23T12:29:16.833755 #31769] DEBUG -- [req_id cpi-212057]: Trying to find placement for Disk ==> Disk CID: Size:10240 Ephemeral:true Target-DS: my_amazing_datastore_[0-9]{2} Existing-DS:
I, [2018-11-23T12:29:16.833918 #31769]  INFO -- [req_id cpi-212057]: Initiating Disk Allocator with Storage Criteria: Space Req: 10240 Target Pattern: my_amazing_datastore_[0-9]{2}
        Existing-DS Pattern:
D, [2018-11-23T12:29:18.103354 #31769] DEBUG -- [req_id cpi-212057]: Found <Datastore: / my_amazing_datastore_01> for Disk ==> Disk CID: Size:10240 Ephemeral:true Target-DS:my_amazing_datastore_[0-9]{2} Existing-DS:
D, [2018-11-23T12:29:18.103540 #31769] DEBUG -- [req_id cpi-212057]: Initial Storage Options for creating ephemeral disk from pattern: ["my_amazing_datastore_01"]
D, [2018-11-23T12:29:18.103600 #31769] DEBUG -- [req_id cpi-212057]: Storage Options for creating ephemeral disk are: ["my_amazing_datastore_01"]
```

We got down to less than 90Gb free on one datastore today and there's 7.9Tb free on another one?!?!

We have multiple boshes which use the same vCenter IaaS/same Datastores and all the "upgraded" vsphere-cpis appear to be making the same placement errors.

**Expected behavior**
If one datastore is more empty than the others, the vsphere-cpi should make the decision to use it.

**Release Version & Related Info:**
 - CPI Version: v51.0.2
 - BOSH Director Version:  265.11.0
 - Stemcell Name & Version: a range of Trusty and Xenial
 - vCenter Version: 6.5u2c
 - NSX(V) 6.3.6

Many thanks
