### ISSUE TITLE
Failed to create multi-cluster configuration based on cloud-config azs

### ISSUE THREAD

**Issue by ogrand** [cloudfoundry/bosh-vsphere-cpi-release#314]
**Expected behavior**

We want to set vsphere multi-cluster configuration to allow bosh deployments instances creation based on cloud-config azs definitions.

```
Datacenter 01 ==> Cluster 01 ==> Datastore 01
              ==> Cluster 02 ==> Datastore 02
```

`instance-2` (defined on `z2 az`) has to be created on `CLS-02` cluster with persistent disks on `DS-02` datastore.

But when deploying bosh `instance-2`, cpi doesn't use cloud-config azs configuration and creates instance on `CLS-01` cluster with `DS-01` datastore.

```
$ bosh instances

Instance                                         Process State  AZ     IPs  Deployment
instance-1/bb981a9f-55e6-4b8b-94f1-df01558f3daf  running        z1     xxx  test
instance-2/cf6a8991-1ca8-4e7d-a338-076494b7d578  running        z2     xxx  test
```

what's wrong with our configuration ?

**Release Version & Related Info (please complete the following information):**

- Stemcell bionic: 1.34
- bosh: 271.8.0
- CPI: 72
- vCenter Version: 6.7

**bosh deployment manifest**

```
- name: instance-1
  azs:
  - z1
  ...
- name: instance-2
  azs:
  - z2
  ...
```

**bosh director cloud-config**

```
azs:
- name: z1
  cloud_properties:
    datacenters:
      name: DC-01
    - clusters:
      - CLS-01:
          resource_pool: RP-01
- name: z2
  cloud-properties:
    datacenters:
      name: DC-01
    - clusters:
      - CLS-02:
          resource_pool: RP-02
```

**bosh director manifest**

vcenter_ds: `DS-01|DS-02`

`DS-01` datastore is defined on `CLS-01` cluster only  
`DS-02` datastore is defined on `CLS-02` cluster only

```
vcenter:
  address: ((vcenter_ip))
  datacenters:
  - clusters:
    - CLS-01:
        resource_pool: RP-01
    - CLS-02:
        resource_pool: RP-02
    name: ((vcenter_dc))
    datastore_pattern: ((vcenter_ds))
    persistent_datastore_pattern: ((vcenter_ds))
    template_folder: ((vcenter_templates))
    vm_folder: ((vcenter_vms))
    disk_path: ((vcenter_disks))
  user: ((vcenter_user))
  password: ((vcenter_password))
  http_logging: true
  upgrade_hw_version: true
```

**bosh deployment tasks logs**

```
I, [2021-11-17T15:15:01.445512 #19656]  INFO -- [req_id cpi-507207]: Starting create_disk...
I, [2021-11-17T15:15:01.445673 #19656]  INFO -- : Fetching vSphere version to locate SDK
/var/vcap/data/packages/vsphere_cpi/b6197204db823e24a73dd4783eb18d0ceda9f4e4/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2021-11-17T15:15:02.847400 #19656]  INFO -- : Loaded vSphere 6.5 SDK
D, [2021-11-17T15:15:05.314268 #19656] DEBUG -- [req_id cpi-507207]: Running method 'RetrieveServiceContent'...
D, [2021-11-17T15:15:05.377964 #19656] DEBUG -- [req_id cpi-507207]: Running method 'Login'...
I, [2021-11-17T15:15:05.626058 #19656]  INFO -- [req_id cpi-507207]: Cloud properties given : {}
I, [2021-11-17T15:15:05.626231 #19656]  INFO -- [req_id cpi-507207]: Creating disk with size: 3000
I, [2021-11-17T15:15:05.626331 #19656]  INFO -- [req_id cpi-507207]: Using global datastore pattern DS-01|DS-02 and global datastore cluster pattern  persistent: true
I, [2021-11-17T15:15:05.626466 #19656]  INFO -- [req_id cpi-507207]: Initiating Disk Allocator with Storage Criteria: Space Req: 3000 Target Pattern: DS-01|DS-02  Existing-DS Pattern:
I, [2021-11-17T15:15:05.626519 #19656]  INFO -- [req_id cpi-507207]: Gathering storage placement resources for disk allocator pipeline
D, [2021-11-17T15:15:05.626569 #19656] DEBUG -- [req_id cpi-507207]: Gathering storage placement accessible from VM CID: vm-72bc07e0-b477-4ab7-9056-c550460e0b89
D, [2021-11-17T15:15:05.626674 #19656] DEBUG -- [req_id cpi-507207]: Running method 'FindByInventoryPath'...
D, [2021-11-17T15:15:05.638212 #19656] DEBUG -- [req_id cpi-507207]: Running method 'CreateContainerView'...
D, [2021-11-17T15:15:05.751880 #19656] DEBUG -- [req_id cpi-507207]: Running method 'ContinueRetrievePropertiesEx'...
D, [2021-11-17T15:15:06.043124 #19656] DEBUG -- [req_id cpi-507207]: Filter DS-01 for accessibility
I, [2021-11-17T15:15:06.342176 #19656]  INFO -- [req_id cpi-507207]: Trying to create persistent disk on datastore: DS-01
D, [2021-11-17T15:15:06.342379 #19656] DEBUG -- [req_id cpi-507207]: Creating disk 'disk-5dfeeebd-eabe-46c1-bf06-4d21d3bc9802' in datastore 'DS-01'
D, [2021-11-17T15:15:06.342540 #19656] DEBUG -- [req_id cpi-507207]: Running method 'FindByInventoryPath'...
D, [2021-11-17T15:15:06.348131 #19656] DEBUG -- [req_id cpi-507207]: Running method 'MakeDirectory'...
D, [2021-11-17T15:15:06.358224 #19656] DEBUG -- [req_id cpi-507207]: Running method 'CreateVirtualDisk_Task'...
D, [2021-11-17T15:15:06.383650 #19656] DEBUG -- [req_id cpi-507207]: Starting task 'VirtualDiskManager.createVirtualDisk'...
D, [2021-11-17T15:15:07.402766 #19656] DEBUG -- [req_id cpi-507207]: Finished task 'VirtualDiskManager.createVirtualDisk' after 1.018966567 seconds
I, [2021-11-17T15:15:07.402947 #19656]  INFO -- [req_id cpi-507207]: Created disk: #<VSphereCloud::Resources::PersistentDisk:0x0000561b22813c40 @size_in_mb=3000, @datastore=<Datastore: / DS-01>, @folder="Integration/disks", @cid="disk-5dfeeebd-eabe-46c1-bf06-4d21d3bc9802">
I, [2021-11-17T15:15:07.403055 #19656]  INFO -- [req_id cpi-507207]: Finished create_disk in 5.96 seconds
D, [2021-11-17T15:15:07.406692 #19656] DEBUG -- [req_id cpi-507207]: Running method 'Logout'...
I, [2021-11-17T15:15:08.798092 #19663]  INFO -- [req_id cpi-533568]: Starting info...
I, [2021-11-17T15:15:08.798269 #19663]  INFO -- : Fetching vSphere version to locate SDK
I, [2021-11-17T15:15:08.825673 #19663]  INFO -- [req_id cpi-533568]: Finished info in 0.03 seconds
```
