### ISSUE TITLE
ability to specify drs rules without overriding datacenter and cluster

### ISSUE THREAD

**Issue by ozbasarir** [cloudfoundry/bosh-vsphere-cpi-release#85]
currently one has to specify drs rules like following (nested under cluster):

```
cloud_properties:
  datacenters:
  - name: dc1
    clusters:
    - cluster1:
        drs_rules:
        - name: rule1
          type: separate_vms
```

which means that one has to know datacenter and cluster name when specifying it. (typically dc/cluster configuration is specified under an az)

ideally we can specify drs_rules at the top level of cloud properties so that one does not have to know about dc/cluster. example:

```
cloud_properties:
  datacenters:
  - name: dc1
    clusters:
    - cluster1:
  drs_rules:
  - name: rule1
    type: separate_vms
```

this way drs_rules can be specified in a vm_extension without clobbering az configuration (dc/cluster).

cc @cppforlife

**Comment by yeshwantbabar** [comment]
Thanks for the feature request. We already have this in our backlog, this will help us prioritize it.

**Comment by cppforlife** [comment]
@yeshwantbabar would you mind adding a link to tracker item here?

**Comment by yeshwantbabar** [comment]
https://www.pivotaltracker.com/story/show/155381404

**Comment by julian-hj** [comment]
Looking at the story, it appears that this was resolved back in 2018 with a suggestion to use yaml anchors to DRY out the cloud_properties rather than changing the implementation:

The following is possible in the current product:
```
azs:

name: z1
cloud_properties:
  datacenters:
    clusters:
      vcpi-cluster-1:
        drs_rules: &default_drs_rules
        name: 'rule1'
        type: 'separate_vms'
      vcpi-cluster-2:
        drs_rules: *default_drs_rules
```
